# Generated by Django 2.2.2 on 2020-06-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField()),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('descruptions', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showvideo.Video')),
            ],
        ),
    ]
