# Generated by Django 2.2.2 on 2020-06-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showvideo', '0002_auto_20200610_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
    ]
