# Generated by Django 2.2.2 on 2020-06-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showvideo', '0003_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
