# Generated by Django 2.2.2 on 2020-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showvideo', '0004_auto_20200613_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='video',
            name='descruptions',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Нравится'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(help_text='слаг должен быть уникальным', unique=True, verbose_name='СЛАГ'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='urls',
            field=models.URLField(verbose_name='Урл'),
        ),
    ]
