# Generated by Django 2.2.2 on 2020-06-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showvideo', '0005_auto_20200613_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'много видео'},
        ),
    ]
